export const spotifyTrackResponse = {
  items: [
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb',
            },
            href: 'https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb',
            id: '4Z8W4fKeB5YxbusRsdQVPb',
            name: 'Radiohead',
            type: 'artist',
            uri: 'spotify:artist:4Z8W4fKeB5YxbusRsdQVPb',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6GjwtEZcfenmOf6l18N7T7',
        },
        href: 'https://api.spotify.com/v1/albums/6GjwtEZcfenmOf6l18N7T7',
        id: '6GjwtEZcfenmOf6l18N7T7',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b2736c7112082b63beefffe40151',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e026c7112082b63beefffe40151',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d000048516c7112082b63beefffe40151',
            width: 64,
          },
        ],
        name: 'Kid A',
        release_date: '2000-10-02',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:6GjwtEZcfenmOf6l18N7T7',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb',
          },
          href: 'https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb',
          id: '4Z8W4fKeB5YxbusRsdQVPb',
          name: 'Radiohead',
          type: 'artist',
          uri: 'spotify:artist:4Z8W4fKeB5YxbusRsdQVPb',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 200482,
      explicit: false,
      external_ids: {
        isrc: 'GBAYE0800814',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4SrRrB27n7fiRkQcPoKfpk',
      },
      href: 'https://api.spotify.com/v1/tracks/4SrRrB27n7fiRkQcPoKfpk',
      id: '4SrRrB27n7fiRkQcPoKfpk',
      is_local: false,
      name: 'Motion Picture Soundtrack',
      popularity: 61,
      preview_url:
        'https://p.scdn.co/mp3-preview/5164bb66addd0c983fa60e70bf1228ea99f57280?cid=9f105cbebbe446a5ad6df613c4477400',
      track_number: 10,
      type: 'track',
      uri: 'spotify:track:4SrRrB27n7fiRkQcPoKfpk',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
            },
            href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
            id: '7w29UYBi0qsHi5RTcv3lmA',
            name: 'Björk',
            type: 'artist',
            uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
          },
        ],
        available_markets: ['CA', 'US'],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5vBpIxm8ws6pWyVmTWiGE1',
        },
        href: 'https://api.spotify.com/v1/albums/5vBpIxm8ws6pWyVmTWiGE1',
        id: '5vBpIxm8ws6pWyVmTWiGE1',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b2730f11c9a8ad1171690a975a26',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e020f11c9a8ad1171690a975a26',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d000048510f11c9a8ad1171690a975a26',
            width: 64,
          },
        ],
        name: 'Vespertine',
        release_date: '2001',
        release_date_precision: 'year',
        total_tracks: 12,
        type: 'album',
        uri: 'spotify:album:5vBpIxm8ws6pWyVmTWiGE1',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
          },
          href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
          id: '7w29UYBi0qsHi5RTcv3lmA',
          name: 'Björk',
          type: 'artist',
          uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
        },
      ],
      available_markets: ['CA', 'US'],
      disc_number: 1,
      duration_ms: 308933,
      explicit: false,
      external_ids: {
        isrc: 'USEE10100732',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4bZnIdaGBf162pZEkxXSgQ',
      },
      href: 'https://api.spotify.com/v1/tracks/4bZnIdaGBf162pZEkxXSgQ',
      id: '4bZnIdaGBf162pZEkxXSgQ',
      is_local: false,
      name: "It's Not up to You",
      popularity: 44,
      preview_url:
        'https://p.scdn.co/mp3-preview/0f0c15c0c4c08e55c1b026c449cd8ed01836aef8?cid=9f105cbebbe446a5ad6df613c4477400',
      track_number: 3,
      type: 'track',
      uri: 'spotify:track:4bZnIdaGBf162pZEkxXSgQ',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
            },
            href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
            id: '7w29UYBi0qsHi5RTcv3lmA',
            name: 'Björk',
            type: 'artist',
            uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
          },
        ],
        available_markets: ['CA', 'US'],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5vBpIxm8ws6pWyVmTWiGE1',
        },
        href: 'https://api.spotify.com/v1/albums/5vBpIxm8ws6pWyVmTWiGE1',
        id: '5vBpIxm8ws6pWyVmTWiGE1',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b2730f11c9a8ad1171690a975a26',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e020f11c9a8ad1171690a975a26',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d000048510f11c9a8ad1171690a975a26',
            width: 64,
          },
        ],
        name: 'Vespertine',
        release_date: '2001',
        release_date_precision: 'year',
        total_tracks: 12,
        type: 'album',
        uri: 'spotify:album:5vBpIxm8ws6pWyVmTWiGE1',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
          },
          href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
          id: '7w29UYBi0qsHi5RTcv3lmA',
          name: 'Björk',
          type: 'artist',
          uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
        },
      ],
      available_markets: ['CA', 'US'],
      disc_number: 1,
      duration_ms: 160226,
      explicit: false,
      external_ids: {
        isrc: 'USEE10100738',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/6AvwIHTT1u6u4QDucYEgmZ',
      },
      href: 'https://api.spotify.com/v1/tracks/6AvwIHTT1u6u4QDucYEgmZ',
      id: '6AvwIHTT1u6u4QDucYEgmZ',
      is_local: false,
      name: 'Sun in My Mouth',
      popularity: 39,
      preview_url:
        'https://p.scdn.co/mp3-preview/b3f61316be4232e5225f076ee76145054882a411?cid=9f105cbebbe446a5ad6df613c4477400',
      track_number: 9,
      type: 'track',
      uri: 'spotify:track:6AvwIHTT1u6u4QDucYEgmZ',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3sFhA6G1N0gG1pszb6kk1m',
            },
            href: 'https://api.spotify.com/v1/artists/3sFhA6G1N0gG1pszb6kk1m',
            id: '3sFhA6G1N0gG1pszb6kk1m',
            name: 'Wings',
            type: 'artist',
            uri: 'spotify:artist:3sFhA6G1N0gG1pszb6kk1m',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3eN0kcFvDvdpjAvv1qZa4D',
        },
        href: 'https://api.spotify.com/v1/albums/3eN0kcFvDvdpjAvv1qZa4D',
        id: '3eN0kcFvDvdpjAvv1qZa4D',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b27305bdc7164b38b5bbadeb63a3',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e0205bdc7164b38b5bbadeb63a3',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d0000485105bdc7164b38b5bbadeb63a3',
            width: 64,
          },
        ],
        name: 'Wings At The Speed Of Sound (Archive Collection)',
        release_date: '1976-03-25',
        release_date_precision: 'day',
        total_tracks: 18,
        type: 'album',
        uri: 'spotify:album:3eN0kcFvDvdpjAvv1qZa4D',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3sFhA6G1N0gG1pszb6kk1m',
          },
          href: 'https://api.spotify.com/v1/artists/3sFhA6G1N0gG1pszb6kk1m',
          id: '3sFhA6G1N0gG1pszb6kk1m',
          name: 'Wings',
          type: 'artist',
          uri: 'spotify:artist:3sFhA6G1N0gG1pszb6kk1m',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 188360,
      explicit: false,
      external_ids: {
        isrc: 'GBCCS1400016',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/0zUb5MPkQCcDxqTkXiEIud',
      },
      href: 'https://api.spotify.com/v1/tracks/0zUb5MPkQCcDxqTkXiEIud',
      id: '0zUb5MPkQCcDxqTkXiEIud',
      is_local: false,
      name: 'She’s My Baby - 2014 Remaster',
      popularity: 52,
      preview_url:
        'https://p.scdn.co/mp3-preview/71c14da848e97409e184fd623d1d0d104c9dacfb?cid=9f105cbebbe446a5ad6df613c4477400',
      track_number: 3,
      type: 'track',
      uri: 'spotify:track:0zUb5MPkQCcDxqTkXiEIud',
    },
  ],
};

export const spotifyArtistResponse = {
  items: [
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'art pop',
        'electronica',
        'experimental pop',
        'experimental vocal',
        'icelandic experimental',
        'icelandic pop',
        'icelandic singer-songwriter',
        'metropopolis',
        'permanent wave',
        'trip hop',
      ],
      href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
      id: '7w29UYBi0qsHi5RTcv3lmA',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5ebaeb5c04fdd8ec6273850d207',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab67616100005174aeb5c04fdd8ec6273850d207',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f178aeb5c04fdd8ec6273850d207',
          width: 160,
        },
      ],
      name: 'Björk',
      popularity: 62,
      type: 'artist',
      uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'alternative rock',
        'art rock',
        'melancholia',
        'oxford indie',
        'permanent wave',
        'rock',
      ],
      href: 'https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb',
      id: '4Z8W4fKeB5YxbusRsdQVPb',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5eba03696716c9ee605006047fd',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab67616100005174a03696716c9ee605006047fd',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f178a03696716c9ee605006047fd',
          width: 160,
        },
      ],
      name: 'Radiohead',
      popularity: 79,
      type: 'artist',
      uri: 'spotify:artist:4Z8W4fKeB5YxbusRsdQVPb',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'british invasion',
        'classic rock',
        'merseybeat',
        'psychedelic rock',
        'rock',
      ],
      href: 'https://api.spotify.com/v1/artists/3WrFJ7ztbogyGnTHbHJFl2',
      id: '3WrFJ7ztbogyGnTHbHJFl2',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5ebe9348cc01ff5d55971b22433',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab67616100005174e9348cc01ff5d55971b22433',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f178e9348cc01ff5d55971b22433',
          width: 160,
        },
      ],
      name: 'The Beatles',
      popularity: 83,
      type: 'artist',
      uri: 'spotify:artist:3WrFJ7ztbogyGnTHbHJFl2',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/1Cj9j44XMhQeNHAwWJRCKd',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: ['pet calming'],
      href: 'https://api.spotify.com/v1/artists/1Cj9j44XMhQeNHAwWJRCKd',
      id: '1Cj9j44XMhQeNHAwWJRCKd',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5ebd1fb5ab8c7102d3d4e630128',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab67616100005174d1fb5ab8c7102d3d4e630128',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f178d1fb5ab8c7102d3d4e630128',
          width: 160,
        },
      ],
      name: 'Sleepy Dogs',
      popularity: 62,
      type: 'artist',
      uri: 'spotify:artist:1Cj9j44XMhQeNHAwWJRCKd',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/4ZWvN9FEfdTea1SEHjpTNi',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: ['indie rock'],
      href: 'https://api.spotify.com/v1/artists/4ZWvN9FEfdTea1SEHjpTNi',
      id: '4ZWvN9FEfdTea1SEHjpTNi',
      images: [
        {
          height: 667,
          url: 'https://i.scdn.co/image/be1a30d487a842de4846e2e41df16da680116ec5',
          width: 1000,
        },
        {
          height: 427,
          url: 'https://i.scdn.co/image/995a1332a7cae61afce8f1a74efcb8a0d9578b68',
          width: 640,
        },
        {
          height: 133,
          url: 'https://i.scdn.co/image/ccf954cb7b5022e2e4f4c6f7c6caf24b6275dc50',
          width: 200,
        },
        {
          height: 43,
          url: 'https://i.scdn.co/image/830fb0f879b3d3b4b342279b15eb432fcfe62048',
          width: 64,
        },
      ],
      name: 'Pinback',
      popularity: 43,
      type: 'artist',
      uri: 'spotify:artist:4ZWvN9FEfdTea1SEHjpTNi',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/3HJIB8sYPyxrFGuwvKXSLR',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'alternative dance',
        'alternative rock',
        'brooklyn indie',
        'chamber pop',
        'indie rock',
        'indietronica',
        'modern rock',
        'neo-synthpop',
      ],
      href: 'https://api.spotify.com/v1/artists/3HJIB8sYPyxrFGuwvKXSLR',
      id: '3HJIB8sYPyxrFGuwvKXSLR',
      images: [
        {
          height: 667,
          url: 'https://i.scdn.co/image/b13e733ea4dad41a53bf1b4eedb8ba6ca8d3dc84',
          width: 1000,
        },
        {
          height: 427,
          url: 'https://i.scdn.co/image/999ad460fcc88db5be7aa1ffe8f3442331839894',
          width: 640,
        },
        {
          height: 133,
          url: 'https://i.scdn.co/image/f89202009ce77a4163097785d46a0f88ae21aa16',
          width: 200,
        },
        {
          height: 43,
          url: 'https://i.scdn.co/image/becc8fcb3adee80cc3cb95f39d50682fc4fac9ab',
          width: 64,
        },
      ],
      name: 'TV On The Radio',
      popularity: 52,
      type: 'artist',
      uri: 'spotify:artist:3HJIB8sYPyxrFGuwvKXSLR',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/3WaJSfKnzc65VDgmj2zU8B',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'alternative dance',
        'alternative rock',
        'indie rock',
        'indietronica',
        'modern rock',
        'rock',
      ],
      href: 'https://api.spotify.com/v1/artists/3WaJSfKnzc65VDgmj2zU8B',
      id: '3WaJSfKnzc65VDgmj2zU8B',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5ebc31f8e7aad462874455cf070',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab67616100005174c31f8e7aad462874455cf070',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f178c31f8e7aad462874455cf070',
          width: 160,
        },
      ],
      name: 'Interpol',
      popularity: 61,
      type: 'artist',
      uri: 'spotify:artist:3WaJSfKnzc65VDgmj2zU8B',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/7FIoB5PHdrMZVC3q2HE5MS',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'album rock',
        'classic rock',
        'folk rock',
        'mellow gold',
        'rock',
        'singer-songwriter',
        'soft rock',
      ],
      href: 'https://api.spotify.com/v1/artists/7FIoB5PHdrMZVC3q2HE5MS',
      id: '7FIoB5PHdrMZVC3q2HE5MS',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5eb7fda8adcbe0cd99ec83a3bcf',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab676161000051747fda8adcbe0cd99ec83a3bcf',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f1787fda8adcbe0cd99ec83a3bcf',
          width: 160,
        },
      ],
      name: 'George Harrison',
      popularity: 64,
      type: 'artist',
      uri: 'spotify:artist:7FIoB5PHdrMZVC3q2HE5MS',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/64tNsm6TnZe2zpcMVMOoHL',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: [
        'alternative metal',
        'alternative rock',
        'grunge',
        'hard rock',
        'nu metal',
        'rock',
      ],
      href: 'https://api.spotify.com/v1/artists/64tNsm6TnZe2zpcMVMOoHL',
      id: '64tNsm6TnZe2zpcMVMOoHL',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5eb6114a63659d0d5c0a801f733',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab676161000051746114a63659d0d5c0a801f733',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f1786114a63659d0d5c0a801f733',
          width: 160,
        },
      ],
      name: 'Alice In Chains',
      popularity: 69,
      type: 'artist',
      uri: 'spotify:artist:64tNsm6TnZe2zpcMVMOoHL',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1',
      },
      followers: {
        href: null,
        total: 0,
      },
      genres: ['alternative metal', 'nu metal', 'rap metal', 'rock'],
      href: 'https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1',
      id: '5eAWCfyUhZtHHtBdNk56l1',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab6761610000e5eb60063d3451ade8f9fab397c2',
          width: 640,
        },
        {
          height: 320,
          url: 'https://i.scdn.co/image/ab6761610000517460063d3451ade8f9fab397c2',
          width: 320,
        },
        {
          height: 160,
          url: 'https://i.scdn.co/image/ab6761610000f17860063d3451ade8f9fab397c2',
          width: 160,
        },
      ],
      name: 'System Of A Down',
      popularity: 77,
      type: 'artist',
      uri: 'spotify:artist:5eAWCfyUhZtHHtBdNk56l1',
    },
  ],
  total: 50,
  limit: 10,
  offset: 0,
  href: 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=0&time_range=long_term',
  next: 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=10&time_range=long_term',
  previous: null,
};

export const SpotifyWebApiSingleArtist = {
  Artist: {
    external_urls: {
      spotify: 'https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA',
    },
    followers: { href: null, total: 1952908 },
    genres: [
      'art pop',
      'electronica',
      'experimental pop',
      'experimental vocal',
      'icelandic experimental',
      'icelandic pop',
      'icelandic singer-songwriter',
      'metropopolis',
      'permanent wave',
      'trip hop',
    ],
    href: 'https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA',
    id: '7w29UYBi0qsHi5RTcv3lmA',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab6761610000e5ebaeb5c04fdd8ec6273850d207',
        width: 640,
      },
      {
        height: 320,
        url: 'https://i.scdn.co/image/ab67616100005174aeb5c04fdd8ec6273850d207',
        width: 320,
      },
      {
        height: 160,
        url: 'https://i.scdn.co/image/ab6761610000f178aeb5c04fdd8ec6273850d207',
        width: 160,
      },
    ],
    name: 'Björk',
    popularity: 63,
    type: 'artist',
    uri: 'spotify:artist:7w29UYBi0qsHi5RTcv3lmA',
  },
};
