import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notoSerif, publicSans, roboto } from "@/fonts/fonts";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable} 
          ${publicSans.variable} 
          ${notoSerif.variable} 
          ${inter.className}
        `}
      >
        {/* <SessionProvider session={session}> */}
        {children}
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
