import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notoSerif, publicSans, roboto } from "@/fonts/fonts";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/utils/authOptions";
import Navbar from "@/components/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable} 
          ${publicSans.variable} 
          ${notoSerif.variable} 
          ${inter.className}
        `}
      >
        <main className="w-screen min-h-screen bg-dark-200">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
